[tool.poetry]
name = "my_package"
version = "0.0.1"
description = "nice description"
authors = ["mo mo@mo.dk"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "my_package.main:main"
