[project]
name="measurements-mono"
version="0.1.0"
dependencies = [
]
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pydantic>=2.10.15",
]

