name: Notify Team
description: Send an email to a team
inputs:
  team_name:
    description: The name of the team who should receive the email. Used to determine the email address.
    required: true
  subject:
    description: The email subject. Should contain environment information when possible.
    required: true
  email:
    description: Specify to override the email determined by team_name
    required: false
    default: ""
  body:
    description: Additional content for the email body. Apart from this the email body will also always contain a link to the failed build.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Determine email
      id: get_email
      shell: bash
      run: |
        if [ ${{ inputs.email }} != '' ]; then
          team_email=${{ inputs.email }}
        elif [ ${{ inputs.team_name }} == 'Mosaic' ]; then
          team_email=${{ vars.email_mosaic }}
        elif [ ${{ inputs.team_name }} == 'Mandalorian' ]; then
          team_email=${{ vars.email_mandalorian }}
        elif [ ${{ inputs.team_name }} == 'Raccoons' ]; then
          team_email=${{ vars.email_raccoons }}
        elif [ ${{ inputs.team_name }} == 'TheOutlaws' ]; then
          team_email=${{ vars.email_theoutlaws }}
        elif [ ${{ inputs.team_name }} == 'Volt' ]; then
          team_email=${{ vars.email_volt }}
        elif [ ${{ inputs.team_name}} == 'TeamFrontend' ]; then
          team_email=${{ vars.email_teamfrontend }}
        elif [ ${{ inputs.team_name}} == 'TeamEsettDeprecated' ]; then
          team_email=${{ vars.email_teamesettdeprecated }}
        else
          # Fallback
          team_email=${{ vars.email_theoutlaws }}
        fi

        echo "::add-mask::$team_email"
        echo "team_email=$team_email" >>$GITHUB_OUTPUT

    - name: Send email
      uses: Energinet-DataHub/.github/.github/actions/send-email@v14
      with:
        sendgrid-api-key: ${{ secrets.sendgrid_instance_system_notifications_api_key }}
        team-name: ${{ inputs.team_name }}
        to: ${{ steps.get_email.outputs.team_email }}
        from: ${{ vars.email_internal_sender }}
        subject: ${{ inputs.subject }}
        content: ${{ inputs.body }}
