name: Dispatch Deployment Event
description: Dispatch a deployment event
inputs:
  repository_name:
    description: The repository name
    required: true
  name:
    description: The name of the package
    required: true
  app_id:
    description: The app id
    required: true
  private_key:
    description: The private key
    required: true
  repository_path:
    description: The repository path
    required: true
runs:
  using: composite
  steps:
    - name: Find associated pull request
      uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v14
      id: find_pull_request

    - uses: Energinet-DataHub/.github/.github/actions/github-create-token@v14
      name: Generate Github token
      id: generate_token
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: ${{ inputs.repository_path }}
        event-type: ${{ inputs.repository }}-${{ inputs.name }}-deployment-request-domain
        # yamllint disable-line rule:quoted-strings
        client-payload: '{"pr_number": "${{ steps.find_pull_request.outputs.pull_request_number }}", "${{ inputs.name }}": "true"}'
