name: Check and Test

on:
  push:
    branches:
      - sondergaard/python-fun

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test electrical heating entry points
      run: make test_electrical_heating_entry_points
