name: CI Databricks

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        default: latest
      package_name:
        type: string
        required: true

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: |
          cd source/${{ inputs.package_name }}
          uv sync --all-extras --dev

      - uses: astral-sh/ruff-action@v2
        with:
          src: source/${{ inputs.package_name }}

      - name: Run tests
        run: |
          cd source/${{ inputs.package_name }}
          uv run pytest tests

      - name: Build Wheel
        run: |
          cd source/${{ inputs.package_name }}
          uv build

  mypy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Run pip install and mypy check of files in package
        shell: bash
        run: |
          pip install --upgrade pip
          pip install mypy types-python-dateutil
          mypy ./source/${{ inputs.package_name }} --disallow-untyped-defs --ignore-missing-imports

  black_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: --check --diff
          src: ./source/${{ inputs.package_name }}
