name: CI Electrical Heating

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        default: latest

jobs:
  databricks_ci_build:
    uses: Energinet-DataHub/.github/.github/workflows/databricks-build-prerelease.yml@v14
    with:
      python_version: 3.11.7
      architecture: x64
      wheel_working_directory: ./source/electrical_heating
      prerelease_prefix: electrical_heating

  electrical_heating_unit_tests:
    uses: Energinet-DataHub/.github/.github/workflows/python-ci.yml@v14
    with:
      job_name: Unit Tests
      operating_system: dh3-ubuntu-20.04-4core
      path_static_checks: ./source/electrical_heating
      ignore_errors_and_warning_flake8: E501,F401,E402,E203,W503
      tests_folder_path: ./source/electrical_heating/tests
      test_report_path: ./source/electrical_heating/tests
      # See .docker/entrypoint.py on how to use the filter expression
      image_tag: ${{ inputs.image_tag }}

  mypy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Run pip install and mypy check of files in package
        shell: bash
        run: |
          pip install --upgrade pip
          pip install mypy types-python-dateutil
          mypy ./source/electrical_heating --disallow-untyped-defs --ignore-missing-imports

  black_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: --check --diff
          src: ./source/electrical_heating
