name: CI Measurements

on:
  workflow_call: {}

jobs:
  changes:
    uses: ./.github/workflows/detect-changes.yml

  compile_proto_descriptors:
    runs-on: ubuntu-latest
    steps:
      - name: Compile protobuf file descriptors
        shell: bash
        run: |
          pushd './source/measurements/contracts'
          rm -rf ./proto ./assets
          mkdir ./proto ./assets
          cp -r **.proto ./proto
          pushd ./proto
          protoc --include_imports --descriptor_set_out=../assets/persist_submitted_transaction.binpb PersistSubmittedTransaction.proto
          protoc --include_imports --descriptor_set_out=../assets/submitted_transaction_persisted.binpb SubmittedTransactionPersisted.proto
          popd
