name: CI orchestrator

on:
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGES_DIR: source

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v14
    with:
      skip_license_check: true
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  #
  # Compile Protobuf Contracts
  #
  ci_bronze_contracts:
    name: Compile Protobuf Contracts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if contract files has changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            is_changed:
              - source/bronze/src/bronze/infrastructure/contracts/**
      - name: Compile protobuf descriptor files
        uses: ./.github/actions/compile-proto
        if: ${{ steps.changes.outputs.is_changed == 'true' }}

  #
  # Build Package Matrix
  #
  ci_matrix:
    name: Build Package Matrix
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.package_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Discover Pyproject
        uses: ./.github/actions/discover-pyproject
        id: package_matrix
        with:
          path: ${{ env.PACKAGES_DIR }}

  #
  # Test Packages
  #
  ci_test:
    name: Test Packages
    runs-on: ubuntu-24.04
    needs: ci_matrix
    strategy:
      matrix: ${{ fromJson(needs.ci_matrix.outputs.matrix) }}
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Inputs
        run: |
          echo "Path: ${{ matrix.inputs.path }}"
          echo "Name: ${{ matrix.inputs.name }}"

      - name: Check if ${{ matrix.inputs.name }} has changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            is_changed:
              - ${{ matrix.inputs.path }}/**

      - name: Test ${{ matrix.inputs.name }}
        uses: ./.github/actions/uvtest
        if: ${{ steps.changes.outputs.is_changed == 'true' }}
        with:
          name: ${{ matrix.inputs.name }}
          path: ${{ matrix.inputs.path }}

      - name: Find associated pull request
        uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v14
        id: find_pull_request

      - name: Upload prerelease
        uses: ./.github/actions/create-prerelease
        if: ${{ steps.changes.outputs.is_changed == 'true' }}
        with:
          name: ${{ matrix.inputs.name }}
          path: ${{ matrix.inputs.path }}
          issue-number: ${{ steps.find_pull_request.outputs.pull_request_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # ci_bronze:
  #   needs: [changes, ci_docker]
  #   if: ${{ needs.changes.outputs.bronze == 'true' }}
  #   uses: ./.github/workflows/ci-databricks.yml
  #   with:
  #     image_tag: ${{ needs.ci_docker.outputs.image_tag }}
  #     package_name: bronze

  #
  # Branch policy status check
  #
  allow_merge_ci_orchestrator:
    runs-on: ubuntu-24.04
    needs: [ci_base, ci_matrix, ci_test, ci_bronze_contracts]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
