name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.
# It should be used by the 'ci-orchestrator.yml' and 'cd.yml' to ensure they both use
# the same path's to detect changes.

on:
  workflow_call:
    outputs:
      any:
        value: ${{ jobs.changes.outputs.any }}
      electrical_heating_job:
        value: ${{ jobs.changes.outputs.electrical_heating_job }}
      docker:
        value: ${{ jobs.changes.outputs.docker }}
      docker_in_commit:
        value: ${{ jobs.changes.outputs.docker_in_commit }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      any: ${{ steps.filter.outputs.any }}
      electrical_heating_job: ${{ steps.filter.outputs.electrical_heating_job }}
      docker: ${{ steps.filter.outputs.docker }}
      docker_in_commit: ${{ steps.docker_changed.outputs.any_changed }}
    steps:
      # For pull requests it's not necessary to checkout the code because GitHub REST API is used to determine changes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            any:
              - '.github/workflows/cd.yml'
              - '.github/workflows/ci-electrical-heating.yml'
              - '.devcontainer/docker-compose.yml'
              - '.docker/requirements.txt'
              - 'source/electrical_heating/**'
            electrical_heating_job:
              - 'source/electrical_heating/electrical_heating_job/**'
            docker:
              - .docker/**

      - name: Package content or build has changed
        id: docker_changed
        uses: tj-actions/changed-files@v41
        with:
          since_last_remote_commit: true
          files: .docker/**
