name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.
# It should be used by the 'ci-orchestrator.yml' and 'cd.yml' to ensure they both use
# the same path's to detect changes.

on:
  workflow_call:
    outputs:
      any_databricks:
        value: ${{ jobs.changes.outputs.any_databricks }}
      electrical_heating:
        value: ${{ jobs.changes.outputs.electrical_heating }}
      effect_settlement:
        value: ${{ jobs.changes.outputs.effect_settlement }}
      docker:
        value: ${{ jobs.changes.outputs.docker }}
      docker_in_commit:
        value: ${{ jobs.changes.outputs.docker_in_commit }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      any_databricks: ${{ steps.filter.outputs.any_databricks }}
      electrical_heating: ${{ steps.filter.outputs.electrical_heating }}
      effect_settlement: ${{ steps.filter.outputs.effect_settlement }}
      docker: ${{ steps.filter.outputs.docker }}
      docker_in_commit: ${{ steps.docker_changed.outputs.any_changed }}
    steps:
      # For pull requests it's not necessary to checkout the code because GitHub REST API is used to determine changes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            any_databricks:
              - '.github/workflows/cd.yml'
            electrical_heating:
              - 'source/electrical_heating/**'
              - '.github/workflows/ci-electrical-heating.yml'
            effect_settlement:
              - 'source/effect_settlement/**'
              - '.github/workflows/ci-effect-settlement.yml'
            docker:
              - .docker/**
              - '.devcontainer/**'

      - name: Package content or build has changed
        id: docker_changed
        uses: tj-actions/changed-files@v41
        with:
          since_last_remote_commit: true
          files: .docker/**
